import { Grid } from "@mui/material";
import RecipeThumbnail from "../components/RecipeThumbnail";
import { RecipeType } from "../types";

export const Search = () => {
    const searchResults: RecipeType[] = [
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
        {
            id: 1,
            title: "Chicken Katsu",
            image: "https://t3.ftcdn.net/jpg/03/69/57/26/360_F_369572634_6m2igusHcoqUhutoFmxtJIMgI1DsxtCt.jpg",
            imageType: "jpg",
            extendedIngredients: [
                {
                    id: 1,
                    original: "1 cup of milk",
                    originalName: "milk",
                },
                {
                    id: 2,
                    original: "1 cup of flour",
                    originalName: "flour",
                },
            ],
            preparationMinutes: 10,
            cookingMinutes: 20,
            sourceUrl: "google.com",
            instructions: "Mix the milk and flour. Fry the chicken. Eat",
            servings: 4,
            cuisines: ["test"],
            dishTypes: ["test"],
            summary: "Chicken Katsu the way my grandma makes it",
        },
    ];

    return (
        <div>
            <h1>Search</h1>
            {/* make a grid of RecipeThumbnail cards */}
            <Grid
                container
                direction="row"
                gap={5}
                columns={5}
                gridAutoRows="auto"
                justifyContent="center"
                alignItems="center"
            >
                {searchResults.map((recipe) => (
                    <Grid item xs={1}>
                        <RecipeThumbnail recipe={recipe} />
                    </Grid>
                ))}
            </Grid>
        </div>
    );
};

export default Search;
